### ISSUE TITLE
需求用例表格填写

### ISSUE THREAD

**Issue by LW-Ricarido** [buaatechshare/requirement-investigation#2]
- [x] A01,A02,A03  @vermouthdky 
- [x] A04,A05,B01  @cheng052 
- [x] B04,B05,B06 @RightChris 
- [x] B02,B03,B14 @Skyvot 
- [x] B07,B08,B09 @silveryshine 
- [x] B10,B11,B12 @Lym666XD 
- [x] B13,D01,D02 @naykun 
- [x] C01,C02 @zyh1019179614 
- [x] D03,D04,D05 @LW-Ricarido

**Comment by zyh1019179614** [comment]
add C01C02

**Comment by Skyvot** [comment]
#6 add B02B03B14
